
// BusinessBuilder

export const ADD_BUSINESS = 'ADD_BUSINESS'; 
export const SWITCH_BUSINESS_TAB = 'SWITCH_BUSINESS_TAB'; 
export const DELETE_BUSINESS = 'DELETE_BUSINESS'; //
export const ADD_WORKING_HOURS = 'ADD_WORKING_HOURS'; //

export const FETCH_BUSINESSDATA_BEGIN   = 'FETCH_BUSINESSDATA_BEGIN'; //
export const FETCH_BUSINESSDATA_SUCCESS = 'FETCH_BUSINESSDATA_SUCCESS'; //
export const FETCH_BUSINESSDATA_FAILURE = 'FETCH_BUSINESSDATA_FAILURE'; //

export const CLEAR_STATE = 'CLEAR_STATE'; // *

// STOPWATCHES

export const INITIALIZE_STOPWATCHES_START = 'INITIALIZE_STOPWATCHES_START'; 
export const INITIALIZE_STOPWATCHES_SUCCESS = 'INITIALIZE_STOPWATCHES_SUCCESS'; 

export const SAVE_CURRENT_STOPWATCH_TIME = 'SAVE_CURRENT_STOPWATCH_TIME'; 
export const CLEAR_CURRENT_STOPWATCH_TIME = 'CLEAR_CURRENT_STOPWATCH_TIME'; 
export const SAVE_TIMER_TIME = 'SAVE_TIMER_TIME'; 
export const UPDATE_STOPWATCH = 'UPDATE_STOPWATCH';
export const CLEAR_STOPWATCH = 'CLEAR_STOPWATCH'; 

// Auth

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CLEAR_ERROR = 'CLEAR_ERROR';


// Temporarily not used

export const CLEAR_CURRENT_COUNTDOWN_TIME = 'CLEAR_CURRENT_COUNTDOWN_TIME';
export const STOPWATCH_OR_COUNTDOWN_IS_SHOWN_HANDLER = 'STOPWATCH_OR_COUNTDOWN_IS_SHOWN_HANDLER';
export const SAVE_CURRENT_MINI_STOPWATCH_TIME = 'SAVE_CURRENT_MINI_STOPWATCH_TIME';
export const INCREASE_TIMER = 'INCREASE_TIMER';
export const SAVE_TIMER_ID = 'SAVE_TIMER_ID';
